# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccrider" do
  version "1.11.1"

  on_macos do
    on_arm do
      sha256 "9c863cea5698a7b440c0bba523d6a244a6c44e38fa71e90ae1265391e735b3e5"
      url "https://github.com/neilberkman/ccrider/releases/download/v1.11.1/ccrider_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d093d99e819526ba4c6e5a1cdc7f3a6dfce1a11528e4c635014ee591c9439bb6"
      url "https://github.com/neilberkman/ccrider/releases/download/v1.11.1/ccrider_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e81e53881cab1b60b86f3820c7cabd3f97ab776f225746e586b3a447c4ef62c3"
      url "https://github.com/neilberkman/ccrider/releases/download/v1.11.1/ccrider_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3b95bbcbe7337223c59e62e1216d1514b75722c1323ad1006faf06082db4053a"
      url "https://github.com/neilberkman/ccrider/releases/download/v1.11.1/ccrider_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ccrider"
  desc "Search, browse, and resume your coding agent sessions"
  homepage "https://github.com/neilberkman/ccrider"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccrider"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ccrider"]
    end
  end

  # No zap stanza required
end
