# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccrider" do
  version "1.13.0"

  on_macos do
    on_arm do
      sha256 "eba939ca0f6abbc03d673bc9475622b06f5904acd881df7ee103cf4a6f2b0db0"
      url "https://github.com/neilberkman/ccrider/releases/download/v#{version}/ccrider_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d32df5cf821cad5a35023bf48c9940474a2ccaf1ab0a74f1864005fcf24537a7"
      url "https://github.com/neilberkman/ccrider/releases/download/v#{version}/ccrider_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ca75d6b7934d3e78e9eb2b522dd84ff63debed75512fe51bdb32cf66c99202ff"
      url "https://github.com/neilberkman/ccrider/releases/download/v#{version}/ccrider_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "caf51ffb31189299bf95e88b0b45a7ba3cce463be0b06dbede1b8bdb302a34d3"
      url "https://github.com/neilberkman/ccrider/releases/download/v#{version}/ccrider_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ccrider"
  desc "Search, browse, and resume your coding agent sessions"
  homepage "https://github.com/neilberkman/ccrider"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccrider"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ccrider"]
    end
  end

  # No zap stanza required
end
