# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccrider" do
  version "1.12.0"

  on_macos do
    on_arm do
      sha256 "f80df9fc18ad6c22f183ecee99a46a0bb9469dcd9407a78076b10625e284ee01"
      url "https://github.com/neilberkman/ccrider/releases/download/v#{version}/ccrider_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "69b245e9ccb40d7be69d5bc6df5405da578d121ac57022a5c5a502aa76cee96f"
      url "https://github.com/neilberkman/ccrider/releases/download/v#{version}/ccrider_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e1e7b783f5173b4caaf9f809e6dbf085e8bed0c0a43a10cdf46589942498287d"
      url "https://github.com/neilberkman/ccrider/releases/download/v#{version}/ccrider_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b69ed8339a8c076ae9884f14afd43769e720b7ec53c107915d13183e46297f6f"
      url "https://github.com/neilberkman/ccrider/releases/download/v#{version}/ccrider_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ccrider"
  desc "Search, browse, and resume your coding agent sessions"
  homepage "https://github.com/neilberkman/ccrider"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccrider"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ccrider"]
    end
  end

  # No zap stanza required
end
