# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccrider < Formula
  desc "Search, browse, and resume your Claude Code sessions"
  homepage "https://github.com/neilberkman/ccrider"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neilberkman/ccrider/releases/download/v1.2.1/ccrider_1.2.1_darwin_amd64.tar.gz"
      sha256 "f0ef3220a42e8c280a919d2527460940ccc478cd63559f8570bf2a9a4fd4d2b8"

      define_method(:install) do
        bin.install "ccrider"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neilberkman/ccrider/releases/download/v1.2.1/ccrider_1.2.1_darwin_arm64.tar.gz"
      sha256 "a8c205f88d810d7d0dd8fb4ae6a3a10474ee413d99de122ebf62cd6fdad1361a"

      define_method(:install) do
        bin.install "ccrider"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilberkman/ccrider/releases/download/v1.2.1/ccrider_1.2.1_linux_amd64.tar.gz"
      sha256 "f7a940a2e9305e0f2607209fa5a957581eef6fe57e3a90dceb6984e6c0372ac1"
      define_method(:install) do
        bin.install "ccrider"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilberkman/ccrider/releases/download/v1.2.1/ccrider_1.2.1_linux_arm64.tar.gz"
      sha256 "971d4a0b42ee27afd4b071ca8dff26b736158996557badb84c252887d661fee0"
      define_method(:install) do
        bin.install "ccrider"
      end
    end
  end

  test do
    system "#{bin}/ccrider", "--version"
  end
end
