# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccrider < Formula
  desc "Search, browse, and resume your Claude Code sessions"
  homepage "https://github.com/neilberkman/ccrider"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neilberkman/ccrider/releases/download/v1.1.0/ccrider_1.1.0_darwin_amd64.tar.gz"
      sha256 "762533d667bcd05129c465d3301ff372ba75d9bec49c36213501405a4724bdcd"

      define_method(:install) do
        bin.install "ccrider"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neilberkman/ccrider/releases/download/v1.1.0/ccrider_1.1.0_darwin_arm64.tar.gz"
      sha256 "e11f9e7ffcf75d0f446fb61f64e6e80f3068dc8aa60155e1833a53965fe63d86"

      define_method(:install) do
        bin.install "ccrider"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilberkman/ccrider/releases/download/v1.1.0/ccrider_1.1.0_linux_amd64.tar.gz"
      sha256 "c062b3cbc2244b08ed57b636b7dd55b498f422592be6f6387202617ec119c94a"
      define_method(:install) do
        bin.install "ccrider"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilberkman/ccrider/releases/download/v1.1.0/ccrider_1.1.0_linux_arm64.tar.gz"
      sha256 "8e1ab3fd72d5caa98b2213ec554d712c8aaff000a96e3450e652a95a14d7ffbb"
      define_method(:install) do
        bin.install "ccrider"
      end
    end
  end

  test do
    system "#{bin}/ccrider", "--version"
  end
end
