# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccrider < Formula
  desc "Search, browse, and resume your coding agent sessions"
  homepage "https://github.com/neilberkman/ccrider"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neilberkman/ccrider/releases/download/v1.6.0/ccrider_1.6.0_darwin_amd64.tar.gz"
      sha256 "8ad0ff998df1b926d62ef5577d1c970b9cab1d4102b0485e6131ef34ef530957"

      define_method(:install) do
        bin.install "ccrider"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neilberkman/ccrider/releases/download/v1.6.0/ccrider_1.6.0_darwin_arm64.tar.gz"
      sha256 "6239d06f848989561d6867e34b0b95944d8770a59a9a0b4be3da3f7ce646895e"

      define_method(:install) do
        bin.install "ccrider"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilberkman/ccrider/releases/download/v1.6.0/ccrider_1.6.0_linux_amd64.tar.gz"
      sha256 "726cf8401b2e8592d9d3831734daa1091a9415ab1a909e05457d9a176567fd1a"
      define_method(:install) do
        bin.install "ccrider"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilberkman/ccrider/releases/download/v1.6.0/ccrider_1.6.0_linux_arm64.tar.gz"
      sha256 "74fb08063467f3a6a71131f0e3531d60fcf887e3be4a80e9d533c167c6eea828"
      define_method(:install) do
        bin.install "ccrider"
      end
    end
  end

  test do
    system "#{bin}/ccrider", "--version"
  end
end
